In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
np.asarray(l)

array([1, 2, 3, 4])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
np.zeros((4,5))+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [17]:
np.empty((2,4)) #generate random values which are very small

array([[0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 6.225e-321, 0.000e+000, 0.000e+000]])

In [18]:
np.linspace(4,6) #generates no between starting point and end point. default is 50 nos

array([4.        , 4.04081633, 4.08163265, 4.12244898, 4.16326531,
       4.20408163, 4.24489796, 4.28571429, 4.32653061, 4.36734694,
       4.40816327, 4.44897959, 4.48979592, 4.53061224, 4.57142857,
       4.6122449 , 4.65306122, 4.69387755, 4.73469388, 4.7755102 ,
       4.81632653, 4.85714286, 4.89795918, 4.93877551, 4.97959184,
       5.02040816, 5.06122449, 5.10204082, 5.14285714, 5.18367347,
       5.2244898 , 5.26530612, 5.30612245, 5.34693878, 5.3877551 ,
       5.42857143, 5.46938776, 5.51020408, 5.55102041, 5.59183673,
       5.63265306, 5.67346939, 5.71428571, 5.75510204, 5.79591837,
       5.83673469, 5.87755102, 5.91836735, 5.95918367, 6.        ])

In [19]:
np.linspace(2,6,40)

array([2.        , 2.1025641 , 2.20512821, 2.30769231, 2.41025641,
       2.51282051, 2.61538462, 2.71794872, 2.82051282, 2.92307692,
       3.02564103, 3.12820513, 3.23076923, 3.33333333, 3.43589744,
       3.53846154, 3.64102564, 3.74358974, 3.84615385, 3.94871795,
       4.05128205, 4.15384615, 4.25641026, 4.35897436, 4.46153846,
       4.56410256, 4.66666667, 4.76923077, 4.87179487, 4.97435897,
       5.07692308, 5.17948718, 5.28205128, 5.38461538, 5.48717949,
       5.58974359, 5.69230769, 5.79487179, 5.8974359 , 6.        ])

In [22]:
np.linspace(2,6,10).reshape(2,5)

array([[2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778],
       [4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]])

In [23]:
np.linspace(2,6,10,endpoint=False) #does not include the last no

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6])

In [24]:
np.linspace(2,6,endpoint=False, retstep=False)

array([2.  , 2.08, 2.16, 2.24, 2.32, 2.4 , 2.48, 2.56, 2.64, 2.72, 2.8 ,
       2.88, 2.96, 3.04, 3.12, 3.2 , 3.28, 3.36, 3.44, 3.52, 3.6 , 3.68,
       3.76, 3.84, 3.92, 4.  , 4.08, 4.16, 4.24, 4.32, 4.4 , 4.48, 4.56,
       4.64, 4.72, 4.8 , 4.88, 4.96, 5.04, 5.12, 5.2 , 5.28, 5.36, 5.44,
       5.52, 5.6 , 5.68, 5.76, 5.84, 5.92])

In [25]:
np.logspace(2,4,10,base=10) #generate an array of log values

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [31]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
a.max()

15

In [37]:
b=np.arange(4,40).reshape(6,6)
b

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [42]:
b.max(axis=0) #row wise comparison

array([34, 35, 36, 37, 38, 39])

In [43]:
b.max(axis=1) #column wise comparison

array([ 9, 15, 21, 27, 33, 39])

In [44]:
b

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [50]:
a=np.array([1,2,3,1,2,3])
a

array([1, 2, 3, 1, 2, 3])

In [51]:
a+b

array([[ 5,  7,  9,  8, 10, 12],
       [11, 13, 15, 14, 16, 18],
       [17, 19, 21, 20, 22, 24],
       [23, 25, 27, 26, 28, 30],
       [29, 31, 33, 32, 34, 36],
       [35, 37, 39, 38, 40, 42]])

In [52]:
a.T

array([1, 2, 3, 1, 2, 3])

In [56]:
a=a.reshape(1,-1)
a

array([[1, 2, 3, 1, 2, 3]])

In [57]:
a.T

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [58]:
a+b

array([[ 5,  7,  9,  8, 10, 12],
       [11, 13, 15, 14, 16, 18],
       [17, 19, 21, 20, 22, 24],
       [23, 25, 27, 26, 28, 30],
       [29, 31, 33, 32, 34, 36],
       [35, 37, 39, 38, 40, 42]])

In [59]:
np.sqrt(b)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [60]:
np.exp(b)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [61]:
np.log10(b)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [62]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [63]:
y=x #shallow copy - any change in x will reflect in y
y

array([1, 2, 3])

In [64]:
z=np.copy(x) #deep copy - any change in x will not reflect in z
z

array([1, 2, 3])

In [65]:
x[0]=100
x

array([100,   2,   3])

In [66]:
y #y is reffering to the same memory location as x 

#any change in x will reflect in y also (y=x)

array([100,   2,   3])

In [67]:
z

array([1, 2, 3])

In [68]:
id(x) #returns the identity of object

791204619824

In [69]:
id(y)

791204619824

In [70]:
id(z)

791201578896

In [71]:
id(x[0])

791201574832

In [72]:
id(y[0])

791201476752

In [73]:
id(x[0])==id(y[0]) #id(x) and id(y) is different but still it is giving true

True

In [74]:
id(x)==id(z)

False